### ISSUE TITLE
Add image for latest 2.8.x

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-rock#21]
The charm is still on 2.8.x, but there is no PR for 2.8.6, [only 2.9.x](https://github.com/canonical/loki-rock/pulls).
We need a 2.8.6 image (bunch of CVEs).

**Comment by lucabello** [comment]
Do we actually need `2.8.6`? Is there a problem with just using `2.9.x`?

**Comment by sed-i** [comment]
As soon as we have a 2.9 workload in stable, we could close this issue.
